# ==============================================================
#  configs_fedpalm.py — hyperparameters for FedPalm
#  Yang et al., "FedPalm", TIFS 2026
#  Adapted for CASIA-MS / XJTU open-set cross-domain evaluation
# ==============================================================

# XJTU domain definitions — 4 clients, one per (smartphone, lighting) pair
XJTU_VARIATIONS = [
    ("iPhone", "Flash"),
    ("iPhone", "Nature"),
    ("huawei", "Flash"),
    ("huawei", "Nature"),
]

CONFIG_FEDPALM = {
    # ── Dataset selection ──────────────────────────────────────
    # "casiams" : 6 clients, one per spectral band
    # "xjtu"    : 4 clients, one per (smartphone, lighting) domain
    "dataset"          : "casiams",

    # ── Paths ──────────────────────────────────────────────────
    "data_root"        : "/home/pai-ng/Jamal/CASIA-MS-ROI",
    "xjtu_data_root"   : "/home/pai-ng/Jamal/XJTU-UP",

    "base_results_dir" : "./rst_fedpalm_{dataset}",

    # Shared splits for fair comparison (same as main framework)
    # Reuses splits generated by main.py so identity partitioning
    # is identical between FedPalm and your baseline runs.
    "splits_path"      : "./rst_fedavg_{dataset}/splits.pkl",

    # ── Dataset ────────────────────────────────────────────────
    "n_ids"            : 200,    # number of identities to sample
    "k_test"           : 0.20,   # fraction of IDs allocated to test set
    "gallery_ratio"    : 0.20,   # fraction of test-ID samples → gallery

    # ── Model (fixed — FedPalm uses CompNet backbone) ──────────
    # compnet_fedpalm is the original FedPalm backbone:
    #   CB1 // CB2 // CB3 → concat [B, 9708]
    #   → fc_brand (9708→512) → drop → arclayer_brand (ArcFace)
    # Both local and anchor models use this architecture.
    "img_side"         : 128,
    "embedding_dim"    : 512,
    "dropout"          : 0.25,
    "arcface_s"        : 30.0,
    "arcface_m"        : 0.50,

    # ── FedPalm architecture ───────────────────────────────────
    # Each client maintains two model copies:
    #   local model  (θ_i) — personalized textural expert, never shared
    #   anchor model (φ_i) — shared textural expert, FedAvg'd each round
    # The server holds Φ = FedAvg({φ_i}), distributed back each round.
    #
    # Textural Expert Interaction Module (TEIM):
    #   For each sample, fe_orig from local model is routed through
    #   other clients' local models (frozen). The top-k most similar
    #   features are weighted-combined with fe_orig:
    #     sim_fe = 0.8×fe_orig + 0.1×top1_fe + 0.1×top2_fe
    #   Final embedding: 0.8×anchor_fe + 0.2×sim_fe
    "teim_blend_anchor" : 0.8,    # weight on anchor feature in final embed
    "teim_blend_side"   : 0.2,    # weight on TEIM feature in final embed
    "teim_self_weight"  : 0.8,    # weight on self feature in sim_fe
    "teim_top1_weight"  : 0.1,    # weight on top-1 similar feature
    "teim_top2_weight"  : 0.1,    # weight on top-2 similar feature

    # ── Loss functions ─────────────────────────────────────────
    # FedPalm total loss per client per batch:
    #   L = w1 × CE(local, y)
    #     + w2 × SupCon([final_fe, final_fe'], y)
    #     + w1 × CE(anchor, y)
    # CE uses ArcFace logits; SupCon uses the blended TEIM embeddings
    # of two augmented views of the same identities.
    "w1"               : 0.8,    # weight for CE losses (local + anchor)
    "w2"               : 0.2,    # weight for SupCon loss
    "temperature"      : 0.07,   # SupCon temperature

    # ── Aggregation ────────────────────────────────────────────
    # Only anchor models are aggregated; local models stay private.
    # This is the key departure from standard FedAvg:
    #   fedavg_anchors: Φ ← (1/n)·Σ φ_i  →  broadcast to all φ_i
    #   local models θ_i: untouched, accumulate domain-specific knowledge
    # FedAvg weights are uniform (1/n_clients) across all clients.
    "fedavg_weights"   : "uniform",   # only "uniform" supported

    # ── FL hyperparameters ─────────────────────────────────────
    "n_rounds"         : 50,
    "local_epochs"     : 1,      # E: local training epochs per round
    #   Note: FedPalm trains local and anchor models for local_epochs
    #   on each client per round before aggregation.

    # ── Training ───────────────────────────────────────────────
    "batch_size"       : 64,
    "lr"               : 0.001,
    "lr_step"          : 30,     # StepLR: reduce lr every lr_step rounds
    "lr_gamma"         : 0.8,    # StepLR: multiply lr by lr_gamma

    # ── Evaluation ─────────────────────────────────────────────
    # Three modes reported every round:
    #   "global"      → server model (aggregated anchors) only
    #   "local_avg"   → mean embedding from all local models
    #   "full_fedpalm"→ 0.8×anchor + 0.2×TEIM (full pipeline)
    "eval_global"      : True,
    "eval_local_avg"   : True,
    "eval_full"        : True,
    "avg_last_rounds"  : 5,      # rounds to average for final reporting

    # ── Misc ───────────────────────────────────────────────────
    "random_seed"      : 42,
    "num_workers"      : 4,
}
